services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - WEB_ORIGIN=http://localhost:5173
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_SCOPES=repo
      - BASE_URL=http://localhost:4000
      - SESSION_SECRET=dev
      - AI_PROVIDER=gemini
      - AI_API_KEY=
  web:
    build:
      context: ..
      dockerfile: docker/web.Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
